# Generated by Django 5.2.6 on 2025-09-19 19:53

from django.db import migrations

def set_new_building_based_on_year(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    for flat in Flat.objects.all():
        if flat.construction_year is not None:
            flat.new_building = (flat.construction_year >= 2015)
        else:
            flat.new_building = False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_based_on_year)
    ]
