# Generated by Django 5.2.6 on 2025-09-19 20:17

from django.db import migrations
import phonenumbers

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_number):
                    formatted_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                    flat.owner_pure_phone = formatted_number
                else:
                    flat.owner_pure_phone = None
            except phonenumbers.NumberParseException:
                flat.owner_pure_phone = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]


