# Generated by Django 5.2.6 on 2025-09-19 20:49

from django.db import migrations

def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone,
        )
        owner.flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250919_2328'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners, reverse_code=migrations.RunPython.noop),
    ]
